@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Library *-right-> "1" UniqueBookmarkList
Library *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueBookmarkList
UniqueTagList -[hidden]down- UniqueBookmarkList

UniqueTagList -right-> "*" Tag
UniqueBookmarkList -right-> Bookmark

Bookmark -up-> "*" Tag

Bookmark *--> Name
Bookmark *--> Phone
Bookmark *--> Email
Bookmark *--> Address
@enduml
