@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyLibrary" as ReadOnlyLibrary
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Library
Class ModelManager
Class UserPrefs

Class UniqueBookmarkList
Class Bookmark
Class Address
Class Email
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Library .up.|> ReadOnlyLibrary

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyLibrary
ModelManager -left-> "1" Library
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Library *--> "1" UniqueBookmarkList
UniqueBookmarkList --> "~* all" Bookmark
Bookmark *--> Name
Bookmark *--> Phone
Bookmark *--> Email
Bookmark *--> Address
Bookmark *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Bookmark
@enduml
